# Generated by Django 3.2.5 on 2021-07-10 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='excerpt',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='headline',
            field=models.TextField(),
        ),
    ]
