# Generated by Django 3.2.5 on 2021-07-11 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20210710_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.FileField(upload_to='https://chase-youth.s3.us-east-2.amazonaws.com/events'),
        ),
    ]
