# Generated by Django 3.2.5 on 2021-07-11 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description_2',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='description_3',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='description_4',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='description_5',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.FileField(upload_to='events'),
        ),
    ]
