# Generated by Django 3.2.5 on 2021-07-11 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20210711_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
