# Generated by Django 3.2.5 on 2021-07-12 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('image', models.FileField(upload_to='staff')),
                ('role', models.CharField(max_length=20)),
                ('intro', models.TextField()),
                ('bio', models.TextField()),
            ],
        ),
    ]
