# Generated by Django 3.2.5 on 2021-07-12 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='staff'),
        ),
    ]
