# Generated by Django 3.2.5 on 2021-07-12 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_staff_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
