# Generated by Django 3.2.5 on 2021-07-12 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_alter_staff_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=200),
        ),
    ]
