# Generated by Django 3.2.5 on 2021-07-23 22:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_staff_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='bio',
            new_name='bio1',
        ),
        migrations.AddField(
            model_name='staff',
            name='bio2',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='bio3',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='bio4',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='bio5',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
