# Generated by Django 3.2.5 on 2021-07-23 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_auto_20210723_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='bio2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='bio3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='bio4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='bio5',
            field=models.TextField(blank=True, null=True),
        ),
    ]
