# Generated by Django 3.2.5 on 2021-07-28 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_auto_20210723_2240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name_plural': 'Staff Members'},
        ),
    ]
