# Generated by Django 3.2.5 on 2021-08-06 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_staff_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='bio',
        ),
        migrations.AlterField(
            model_name='staff',
            name='bio1',
            field=models.TextField(),
        ),
    ]
