# Generated by Django 3.2.5 on 2021-08-11 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_staffrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='staff_role',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='staff.staffrole'),
            preserve_default=False,
        ),
    ]
