# Generated by Django 3.2.5 on 2021-08-11 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0010_staff_staff_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='role',
        ),
    ]
