# Generated by Django 3.2.5 on 2021-08-11 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0011_remove_staff_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffrole',
            options={'verbose_name_plural': 'Staff Roles'},
        ),
    ]
