# Generated by Django 3.2.5 on 2021-07-29 23:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'verbose_name_plural': 'Announcement'},
        ),
        migrations.RenameField(
            model_name='announcement',
            old_name='description_text',
            new_name='description_line_1',
        ),
        migrations.AddField(
            model_name='announcement',
            name='description_line_2',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
