# Generated by Django 3.2.5 on 2021-07-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_comment_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(upload_to='blog/post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_display',
            field=models.FileField(upload_to='blog/post'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
