# Generated by Django 3.2.5 on 2021-08-06 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210728_0040'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostTitleFontSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=3)),
            ],
        ),
    ]
