# Generated by Django 3.2.5 on 2021-08-06 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_posttitlefontsize'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posttitlefontsize',
            options={'verbose_name_plural': 'Post Title Font Sizes'},
        ),
        migrations.AddField(
            model_name='post',
            name='post_title_font_sizes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.posttitlefontsize'),
            preserve_default=False,
        ),
    ]
