# Generated by Django 3.2.5 on 2021-08-06 20:21

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_posttitlefontcolor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttitlefontcolor',
            name='value',
            field=colorfield.fields.ColorField(default='#FFFFFF', max_length=18, verbose_name='hexa'),
        ),
    ]
