# Generated by Django 3.2.5 on 2021-08-06 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_posttitlefontcolor_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_title_font_colors',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.posttitlefontcolor'),
            preserve_default=False,
        ),
    ]
