# Generated by Django 3.2.5 on 2021-08-06 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_post_post_title_font_colors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_title_font_colors',
            new_name='post_title_font_color',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_title_font_sizes',
            new_name='post_title_font_size',
        ),
    ]
