# Generated by Django 3.2.5 on 2021-08-09 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20210806_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_display',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_title_font_color',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_title_font_size',
        ),
        migrations.DeleteModel(
            name='PostTitleFontColor',
        ),
        migrations.DeleteModel(
            name='PostTitleFontSize',
        ),
    ]
