# Generated by Django 3.2.5 on 2021-07-28 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=50)),
                ('description1', models.TextField()),
                ('title2', models.CharField(max_length=50)),
                ('description2', models.TextField()),
                ('title3', models.CharField(max_length=50)),
                ('description3', models.TextField()),
                ('story_description1', models.TextField()),
                ('story_description2', models.TextField()),
                ('story_description3', models.TextField()),
                ('story_description4', models.TextField()),
                ('story_description5', models.TextField()),
            ],
        ),
    ]
