# Generated by Django 3.2.5 on 2021-07-28 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'Content', 'verbose_name_plural': 'Manage About Page'},
        ),
        migrations.AlterField(
            model_name='about',
            name='story_description2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='story_description3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='story_description4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='story_description5',
            field=models.TextField(blank=True, null=True),
        ),
    ]
