# Generated by Django 3.2.5 on 2021-08-06 20:42

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkTitleFontColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', colorfield.fields.ColorField(default='#FFFFFF', max_length=18, verbose_name='hexa')),
            ],
            options={
                'verbose_name_plural': 'Work Title Font Colors',
            },
        ),
        migrations.CreateModel(
            name='WorkTitleFontSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=3)),
            ],
            options={
                'verbose_name_plural': 'Work Title Font Sizes',
            },
        ),
    ]
