# Generated by Django 3.2.5 on 2021-08-06 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_worktitlefontcolor_worktitlefontsize'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='post_title_font_color',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='works.worktitlefontcolor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='work',
            name='post_title_font_size',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='works.worktitlefontsize'),
            preserve_default=False,
        ),
    ]
