# Generated by Django 3.2.5 on 2021-08-06 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0003_auto_20210806_2045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='post_title_font_color',
            new_name='work_title_font_color',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='post_title_font_size',
            new_name='work_title_font_size',
        ),
    ]
