# Generated by Django 3.2.5 on 2021-08-07 13:00

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0005_auto_20210807_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcerptFontColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', colorfield.fields.ColorField(default='#FFFFFF', max_length=18, verbose_name='hexa')),
            ],
            options={
                'verbose_name_plural': 'Excerpt Font Colors',
            },
        ),
        migrations.CreateModel(
            name='ExcerptFontSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=3)),
            ],
            options={
                'verbose_name_plural': 'Excerpt Font Sizes',
            },
        ),
    ]
