# Generated by Django 3.2.5 on 2021-08-07 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0006_excerptfontcolor_excerptfontsize'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='excerpt_font_color',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='works.excerptfontcolor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='work',
            name='excerpt_font_size',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='works.excerptfontsize'),
            preserve_default=False,
        ),
    ]
