# Generated by Django 3.2.5 on 2021-08-11 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0007_auto_20210807_1302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='work',
            options={'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
    ]
