# Generated by Django 3.2.5 on 2021-08-12 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0008_alter_work_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='description_1',
            field=models.TextField(blank=True, null=True),
        ),
    ]
